name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Install dependencies
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - run: npm install -g sass
    
    # Build process
    - name: Compile SCSS
      run: sass src/scss:src/css --no-source-map --style=compressed
    
    # Minify JS (add if needed)
    # - run: npm install uglify-js -g
    # - run: uglifyjs src/js/app.js -o dist/js/app.min.js
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src           # Your built files
        keep_files: true             # Preserve existing files
