name: Deploy GPK Ultra

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './'  # Upload entire repository
          
      - name: Deploy
        uses: actions/deploy-pages@v3
