name: Deploy GPK Hub to GitHub Pages

on:
  push:
    branches: [main]
  # Optional: Uncomment if you want manual deploys
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify files
        run: |
          ls -la  # Debug: Show files being deployed
          [ -f index.html ] || exit 1  # Ensure index exists
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
